### ISSUE TITLE
Can't use database in practice 3.

### ISSUE THREAD

**Issue by Bramgus12** [hogeschool/Development--Web#1]
I am following your guide of practice 3 but it keeps giving me the same error:
``` console
C:\Users\bramg\Documents\GitHub\Dev>dotnet ef database update
Applying migration '20191215124228_Initial'.
Failed executing DbCommand (16ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (20191215124228_Initial, 2.1.14-servicing-32113);
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "_Initial"
   at Npgsql.NpgsqlConnector.DoReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadMessage(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications)
   at Npgsql.NpgsqlConnector.ReadExpecting[T](Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)           at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
42601: syntax error at or near "_Initial"
```
In practice 3 you never say when to do another migrations on your database. Maybe you need to do the migrations and database update in the code og practice 2 but that would seem stupid.
Here is my code:
**Startup.cs:**
``` cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Dev.Models;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace Dev
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {

            services.AddDbContext<MovieContext> (
                opt => opt.UseNpgsql(@"Host=localhost;Database=MovieDB;Username=postgres;Password=postgres"));
            
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseMvc();
        }
    }
}

```
**Model.cs:**
``` cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dev.Models
{
public class MovieContext : DbContext
    {
        public DbSet<Movie> Movies { get; set; }
        public DbSet<Actor> Actors { get; set; }
        
        public MovieContext(DbContextOptions<MovieContext> options): base(options)
        {
        }

    }

    public class Actor {
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Birth { get; set; }
        public string Gender { get; set; }
        public int MovieId { get; set; }
        public Movie Movie { get; set; }
    }


    public class Movie {
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Release { get; set; }
        public List<Actor> Actors { get; set; }
    }
}
```

**Dev.csproj:**
``` csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.1.2" PrivateAssets="All" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>

</Project>
```
I have followed your guide carefully but it just doesnt want to do the migrations.

**Comment by Bramgus12** [comment]
@a-omar @mabbadi Could you be able to respond to this. It has already taken two days...

**Comment by a-omar** [comment]
Assuming you are using the migration script from practice 2 in practice 3 after copying the model and the migration folder from practice 2. Delete the migration folder and create the migration script from scratch following the steps mentioned in practice 2.

**Comment by Bramgus12** [comment]
That does nothing. It still gives the error.

**Comment by HamburgerPlsdotexe** [comment]
delete system32

**Comment by a-omar** [comment]
Did you manage to fix it?

**Comment by Bramgus12** [comment]
I still haven't managed to fix it. I might just pop by at school.

**Comment by ThijsOnGitHup** [comment]
I think the problem is that the versions of the Packages in the .csproj are not right or they are incompatible with each other. So make sure you use the right version. Because whe I used the wrong versions i also got the same errors.

**Comment by ThijsOnGitHup** [comment]
Change the versions in the .csproj file. 
Maybe try this:
`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
  </ItemGroup>

</Project>`

**Comment by ThijsOnGitHub** [comment]
I think the versions of the packages are not compatible with each other. Had the same error. Try to set the `<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.0.0" />` to 
`<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="2.1.1" />` 

After you changed it you :
Delete the current migrations.
`dotnet restore`
`dotnet build`
`dotnet ef migrations add "firstCreation"`
`dotnet ef database drop`
`dotnet ef database update`

Worked with me. Hope it works for you.

**Comment by Bramgus12** [comment]
Thanks for the answer. I think it would be nice if the course owner would change these versions to the newer ones.
